// items constants
export const GET_ITEMS_REQUESTED = 'GET_ITEMS_REQUESTED';
export const GET_ITEMS_SUCCESS = 'GET_ITEMS_SUCCESS';
export const GET_ITEMS_FAILED = 'GET_ITEMS_FAILED';

// orders constants
export const GET_ORDERS_REQUESTED = 'GET_ORDERS_REQUESTED';
export const GET_ORDERS_SUCCESS = 'GET_ORDERS_SUCCESS';
export const GET_ORDERS_FAILED = 'GET_ORDERS_FAILED';

export const GET_ORDERS_BY_TIME_PERIOID_REQUESTED = 'GET_ORDERS_BY_TIME_PERIOID_REQUESTED';
export const GET_ORDERS_BY_TIME_PERIOID_SUCCESS = 'GET_ORDERS_BY_TIME_PERIOID_SUCCESS';
export const GET_ORDERS_BY_TIME_PERIOID_FAILED = 'GET_ORDERS_BY_TIME_PERIOID_FAILED';

// branches constants
export const GET_BRANCHES_REQUESTED = 'GET_BRANCHES_REQUESTED';
export const GET_BRANCHES_SUCCESS = 'GET_BRANCHES_SUCCESS';
export const GET_BRANCHES_FAILED = 'GET_BRANCHES_FAILED';

